[pytest]
qt_api = pyqt5
markers =
    slow: mark test as slow to skip it in "normal" testing
    integration: mark test as integration test
    unit: mark test as unit test
addopts = --doctest-modules --doctest-continue-on-failure --benchmark-warmup=on --benchmark-min-rounds=5
filterwarnings =
    ignore:.*:DeprecationWarning
    ignore:.*:PendingDeprecationWarning
