class MatchResult:
    file_path: str
    line_number: int
    line_content: str

class GrepResults:
    matches: list[MatchResult]

def grep(pattern: str, path: str) -> GrepResults: ...
def kill_process(name: str) -> None: ...
def list_entries(path: str) -> list[str]: ...
def list_names(path: str) -> list[str]: ...
