def list_entries(path: str) -> list[str]: ...
def list_names(path: str) -> list[str]: ...
def show_version() -> None: ...
def sum_as_string(a: int, b: int) -> str: ...
def setup_rust_env() -> None: ...
